name: Deploy theme docs

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use yarn
        run: sudo npm i -g yarn

      - name: Install Deps
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build docs
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .vitepress/dist
          ssh-key: ${{ secrets.SSH_TOKEN }}
          repository-name: RimuruW/ArchLinuxGuide
